### ISSUE TITLE
Urho3D/Urho3D.h missing

### ISSUE THREAD

**Issue by ghost** [PeaceSells50/Urho3D#4]
As title says header is not added to repo.

```
#include <Urho3D\Urho3D.h>
```

Unless problem is elsewhere..

Besides use forward-slashes for multi-platform compatibility ;)

EDIT: i was too fast to post an issue, sorry ;)

**Comment by PeaceSells50** [comment]
Maybe too fast, but forward slashes are a very good idea. :)
